function tree1 {
    Write-Host -ForegroundColor white ""
    Write-Host -ForegroundColor yellow "         |         " 
    Write-Host -ForegroundColor yellow "        \|/        " 
    Write-Host -ForegroundColor yellow "       __*__       " 
    Write-Host -NoNewLine -ForegroundColor green "        >" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "       >" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "      >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "     >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "    >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "   >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "  >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "*" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green " >" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor white "        |" 
    Write-Host -NoNewLine -ForegroundColor white " " 
    Write-Host -ForegroundColor white "|" 
    Write-Host -ForegroundColor white "    _ __|_|__ _" 
    Write-Host -ForegroundColor white ""
}
function tree2 {
    Write-Host -ForegroundColor white ""
    Write-Host -ForegroundColor yellow "         |         " 
    Write-Host -ForegroundColor yellow "        \|/        " 
    Write-Host -ForegroundColor yellow "       __.__       " 
    Write-Host -NoNewLine -ForegroundColor green "        >" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "       >" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "      >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "     >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "    >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "   >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "  >" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "." 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green " >" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor blue "O" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor red "@" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor green ">" 
    Write-Host -NoNewLine -ForegroundColor yellow "o" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor green "<" 
    Write-Host -ForegroundColor green "<" 
    Write-Host -NoNewLine -ForegroundColor white "        |" 
    Write-Host -NoNewLine -ForegroundColor white " " 
    Write-Host -ForegroundColor white "|" 
    Write-Host -ForegroundColor white "    _ __|_|__ _" 
    Write-Host -ForegroundColor white ""
}
while ($i) {
    Clear-Host
    tree1
    Start-Sleep 1
    Clear-Host
    tree2
    Start-Sleep 1
 }